[database]
database_host = localhost
database_name = airflow
database_port = 5432
database_username = airflow
database_password = airflow

[file_paths]
input_path = /opt/airflow/data/input
output_path = /opt/airflow/data/output

[bearer_token]
x_token = [YOUR_X_BEARER_TOKEN]

[etl_settings]
batch_size = 100
error_handling = abort
log_level = info

[aws]
aws_access_key_id = [YOUR_AWS_ACCESS]
aws_secret_access_key= [YOUR_AWS_SECRET]
aws_region = us-east-1
aws_bucket_name = tweets-bucket-yourinitials-2025